config/routes.rb
Laboratory::Application.routes.draw do
  

  resources :prms

  # resources :factors


  resources :specimen do
    resources :factors
    resources :shipments do
      resources :fvalues, :only => [:index, :show, :edit, :update]
    end
  end
  # resources :shipments
  match 'specimen/:speciman_id/shipments/:id/passport' => 'shipments#passport', :as => :passport

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  root :to => 'pages#home'
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  belongs_to :speciman
  has_many :fvalues
end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController
  before_filter :get_speciman
  # GET /factors
  # GET /factors.xml
  def index
    @factors = @speciman.factors.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @factors }
    end
  end

  # GET /factors/1
  # GET /factors/1.xml
  def show
    @factor = @speciman.factors.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @factor }
    end
  end

  # GET /factors/new
  # GET /factors/new.xml
  def new
    @factor = @speciman.factors.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @factor }
    end
  end

  # GET /factors/1/edit
  def edit
    @factor = @speciman.factors.find(params[:id])
  end

  # POST /factors
  # POST /factors.xml
  def create
    @factor = @speciman.factors.new(params[:factor])

    respond_to do |format|
      if @factor.save
        format.html { redirect_to([@speciman, @factor], :notice => 'Factor was successfully created.') }
        format.xml  { render :xml => @factor, :status => :created, :location => @factor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @factor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /factors/1
  # PUT /factors/1.xml
  def update
    @factor = @speciman.factors.find(params[:id])

    respond_to do |format|
      if @factor.update_attributes(params[:factor])
        format.html { redirect_to([@speciman, @factor], :notice => 'Factor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @factor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /factors/1
  # DELETE /factors/1.xml
  def destroy
    @factor = @speciman.factors.find(params[:id])
    @factor.destroy

    respond_to do |format|
      format.html { redirect_to(speciman_factors_url(@speciman)) }
      format.xml  { head :ok }
    end
  end

  private

    def get_speciman
      @speciman = Speciman.find params[:speciman_id]
    end

end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/views/factors/_form.html.erb
<%= form_for([@speciman,@factor]) do |f| %>
  <% if @factor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factor.errors.count, "error") %> prohibited this factor from being saved:</h2>

      <ul>
      <% @factor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speciman_id, @speciman.title %><br />
    <%= f.hidden_field :speciman_id %>
  </div>
  <div class="field">
    <%= f.label :j_n, 'Журнал: №п/п' %><br />
    <%= f.text_field :j_n %>
  </div>
  <div class="field">
    <%= f.label :j_title, 'наименование' %><br />
    <%= f.text_field :j_title %>
  </div>
  <div class="field">
    <%= f.label :j_def, 'по умолчанию' %><br />
    <%= f.text_field :j_def %>
  </div>
  <div class="field">
    <%= f.label :pasp_n, 'паспорт: №п/п:' %><br />
    <%= f.text_field :pasp_n %>
  </div>
  <div class="field">
    <%= f.label :pasp_title, 'наименование:' %><br />
    <%= f.text_field :pasp_title %>
  </div>
  <div class="field">
    <%= f.label :pasp_reqmt, 'требования по НТД:' %><br />
    <%= f.text_field :pasp_reqmt %>
  </div>
  <div class="field">
    <%= f.label :pasp_def, 'результаты контроля ОБТК (по умолч):' %><br />
    <%= f.text_field :pasp_def %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factors/edit.html.erb
<h1>Editing factor</h1>

<%= render 'form' %>

<%= link_to 'Show', [@speciman, @factor] %> |
<%= link_to 'Back', speciman_factors_path(@speciman) %>

app/views/factors/index.html.erb
<h1><%= @speciman.title %> <span style='font-size: 0.5em; font-weight: normal;'>показатели</span></h1>

<table>
  <tr class='L2'><th colspan='3'>журнал выпуска</th><th colspan='4' class='nc'>паспорт</th></tr>
  <tr>
    <th>№ п/п</th>
    <th>наименование</th>
    <th>по умолчанию</th>
    <th class='nc'>№ п/п</th>
    <th>наименование</th>
    <th>требования по НТД</th>
    <th>результаты контроля ОБТК</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @speciman.factors.each do |factor| %>
  <tr>
    <td><%= factor.j_n %></td>
    <td><%= factor.j_title %></td>
    <td><%= factor.j_def %></td>
    <td class='nc'><%= factor.pasp_n %></td>
    <td><%= factor.pasp_title %></td>
    <td><%= factor.pasp_reqmt %></td>
    <td><%= factor.pasp_def %></td>
    <td><%= link_to 'Show', [@speciman, factor] %></td>
    <td><%= link_to 'Edit', edit_speciman_factor_path(factor.speciman,factor) %></td>
    <td><%= link_to 'Destroy', speciman_factor_path(@speciman, factor), :method => :delete, :confirm => 'Are you sure?' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "добавить показатель к шаблону '#{@speciman.title}'", new_speciman_factor_path(@speciman) %>

app/views/factors/new.html.erb
<h1>New factor</h1>

<%= render 'form' %>

<%= link_to 'Back', speciman_factors_path(@speciman) %>

app/views/factors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Препарат:</b>
  <%= @factor.speciman.title %>
</p>

<p>
  <b>журнал: №п/п:</b>
  <%= @factor.j_n %>
</p>

<p>
  <b>наименование:</b>
  <%= @factor.j_title %>
</p>

<p>
  <b>по умолчанию:</b>
  <%= @factor.j_def %>
</p>

<p>
  <b>паспорт: №п/п:</b>
  <%= @factor.pasp_n %>
</p>

<p>
  <b>наименование:</b>
  <%= @factor.pasp_title %>
</p>

<p>
  <b>требования по НТД:</b>
  <%= @factor.pasp_reqmt %>
</p>

<p>
  <b>результаты контроля ОБТК (по умолч):</b>
  <%= @factor.pasp_def %>
</p>


<%= link_to 'Edit', edit_speciman_factor_path(@speciman, @factor) %> |
<%= link_to 'Back', speciman_factors_path(@speciman) %>