config/routes.rb
Laboratory::Application.routes.draw do
  

  resources :prms

  # resources :factors


  resources :specimen do
    resources :factors
    resources :shipments do
      resources :fvalues, :only => [:index, :show, :edit, :update]
    end
  end
  # resources :shipments
  match 'specimen/:speciman_id/shipments/:id/passport' => 'shipments#passport', :as => :passport

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  root :to => 'pages#home'
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/specimen_controller.rb
class SpecimenController < ApplicationController
  # GET /specimen
  # GET /specimen.xml
  def index
    @specimen = Speciman.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @specimen }
    end
  end

  # GET /specimen/1
  # GET /specimen/1.xml
  def show
    @speciman = Speciman.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @speciman }
    end
  end

  # GET /specimen/new
  # GET /specimen/new.xml
  def new
    @speciman = Speciman.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @speciman }
    end
  end

  # GET /specimen/1/edit
  def edit
    @speciman = Speciman.find(params[:id])
  end

  # POST /specimen
  # POST /specimen.xml
  def create
    @speciman = Speciman.new(params[:speciman])

    respond_to do |format|
      if @speciman.save
        format.html { redirect_to(specimen_path, :notice => (t 'specimen.notice.created')) }
        format.xml  { render :xml => @speciman, :status => :created, :location => @speciman }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @speciman.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /specimen/1
  # PUT /specimen/1.xml
  def update
    @speciman = Speciman.find(params[:id])

    respond_to do |format|
      if @speciman.update_attributes(params[:speciman])
        format.html { redirect_to(specimen_path, :notice => (t 'specimen.notice.saved')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @speciman.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /specimen/1
  # DELETE /specimen/1.xml
  def destroy
    @speciman = Speciman.find(params[:id])
    @speciman.destroy

    respond_to do |format|
      format.html { redirect_to(specimen_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/specimen_helper.rb
module SpecimenHelper
end

app/views/specimen/_form.html.erb
<%= form_for(@speciman) do |f| %>
  <% if @speciman.errors.any? %>
    <div id="error_explanation">
      <h2><%= t 'specimen.error-msg' %> <%= pluralize(@speciman.errors.count, "") %></h2>

      <ul>
      <% @speciman.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, (t 'specimen.title') %><br />
    <%= f.text_field :title, :size => 125 %>
  </div>
  <div class="field">
    <%= f.label :priord, (t 'specimen.priord') %><br />
    <%= f.text_field :priord, :size => 4 %>
  </div>
  <div class="actions">
    <%= f.submit :value => (t 'specimen.save') %>
  </div>
<% end %>

app/views/specimen/edit.html.erb
<h1><%= t 'nav.Editing' %></h1>

<%= render 'form' %>

<%= link_to (t 'nav.Show'), @speciman %> |
<%= link_to (t 'nav.Back'), specimen_path %> |
<%= link_to (t 'nav.Destroy'), @speciman, :confirm => (t 'nav.del-confirm'), :method => :delete %>

app/views/specimen/index.html.erb
<h1><%= t 'specimen.listing' %> (<%= @specimen.size %>)</h1>

<% form_tag specimen_path, :method => :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag (t "nav.Search"), :name => nil %>
<% end -%>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% tclass = nil %>
<% @specimen.each do |speciman| %>
  <% tclass = (speciman.priord == 0)? nil: " class='fz' " %>
  <tr <%= tclass %> >
    <td><%= link_to (speciman.title), edit_speciman_path(speciman) %></td>
    <td><%= link_to (t 'shipments.nav'), speciman_shipments_path(speciman) %></td>
    <td><%= link_to (t 'factors.title'), speciman_factors_path(speciman) %></td>
    <td><%= nil %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to (t 'specimen.nav-new'), new_speciman_path %>

app/views/specimen/new.html.erb
<h1><%= t 'specimen.new' %></h1>

<%= render 'form' %>

<%= link_to (t 'nav.Back'), specimen_path %>

app/views/specimen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t 'specimen.title' %>:</b>
  <%= @speciman.title %>
</p>

<p>
  <b></b>
  <!-- %= link_to (t 'factors.title'), speciman_factors_path(@speciman) %  -->
</p>


<%= link_to (t 'nav.Edit'), edit_speciman_path(@speciman) %> |
<%= link_to (t 'nav.Back'), specimen_path %>