config/routes.rb
Laboratory::Application.routes.draw do
  

  resources :prms

  # resources :factors


  resources :specimen do
    resources :factors
    resources :shipments do
      resources :fvalues, :only => [:index, :show, :edit, :update]
    end
  end
  # resources :shipments
  match 'specimen/:speciman_id/shipments/:id/passport' => 'shipments#passport', :as => :passport

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  root :to => 'pages#home'
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  belongs_to :speciman
  has_many :fvalues, :dependent => :destroy

  after_create :populate_values

  private

  def populate_values
#    s=Speciman.find 3
#    s.factors.where("j_n is not null").count
#    s.factors.where("j_n is not null").map(&:id).count
    # logger.info ":::: #{speciman.factors.where("j_n IS NOT NULL")}"
    speciman.factors.where("j_n IS NOT NULL").each do |f|
      fvalues.create!(:factor_id => f.id, :fvalue => f.j_def)
    end
    logger.info ":::: created!!"
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_filter :get_speciman
  # GET /shipments
  # GET /shipments.xml
  def passport
    @shipment = @speciman.shipments.find(params[:id])

    respond_to do |format|
      format.html {render :html => :passport, :layout => 'printer'}
      format.xml  { render :xml => @shipments }
    end
    
  end

  def index
    @shipments = @speciman.shipments.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shipments }
    end
  end

  # GET /shipments/1
  # GET /shipments/1.xml
  def show
    @shipment = @speciman.shipments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shipment }
    end
  end

  # GET /shipments/new
  # GET /shipments/new.xml
  def new
    @shipment = @speciman.shipments.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shipment }
    end
  end

  # GET /shipments/1/edit
  def edit
    @shipment = @speciman.shipments.find(params[:id])
  end

  # POST /shipments
  # POST /shipments.xml
  def create
    @shipment = @speciman.shipments.new(params[:shipment])

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to([@speciman, @shipment], :notice => 'Shipment was successfully created.') }
        format.xml  { render :xml => @shipment, :status => :created, :location => @shipment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shipments/1
  # PUT /shipments/1.xml
  def update
    @shipment = @speciman.shipments.find(params[:id])

    respond_to do |format|
      if @shipment.update_attributes(params[:shipment])
        format.html { redirect_to(speciman_shipment_fvalues_path(@speciman, @shipment), :notice => 'Shipment was successfully updated.') }
        # format.html { redirect_to([@speciman, @shipment], :notice => 'Shipment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.xml
  def destroy
    @shipment = @speciman.shipments.find(params[:id])
    @shipment.destroy

    respond_to do |format|
      format.html { redirect_to(speciman_shipments_url(@speciman)) }
      format.xml  { head :ok }
    end
  end

  private

    def get_speciman
      @speciman = Speciman.find params[:speciman_id]
    end

end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/_form.html.erb
<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery("#manufdt").datepicker({ dateFormat: 'yy-mm-dd' });
    jQuery("#releasedt").datepicker({ dateFormat: 'yy-mm-dd' });
    jQuery("#expiredt").datepicker({ dateFormat: 'yy-mm-dd' });
  });
</script>

<%= form_for([@speciman,@shipment]) do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speciman_id, @speciman.title %><br />
    <%= f.hidden_field :speciman_id %>
  </div>
  <div class="field">
    <%= f.label :batch_number, (t 'shipments.batch_number') %><br />
    <%= f.text_field :batch_number %>
  </div>
  <div class="field">
    <%= f.label :check_number, (t 'shipments.check_number') %><br />
    <%= f.text_field :check_number %>
  </div>
  <div class="field">
    <%= f.label :manufdt, (t 'shipments.manufdt') %><br />
    <%= f.text_field :manufdt, :size => 10, :id => 'manufdt', :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :releasedt, (t 'shipments.releasedt') %><br />
    <%= f.text_field :releasedt, :size => 10, :id => 'releasedt', :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :expiredt, (t 'shipments.expiredt') %><br />
    <%= f.text_field :expiredt, :size => 10, :id => 'expiredt', :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit :value => 'Next >' %>
  </div>
<% end %>

app/views/shipments/_shipment.html.erb
<table class='show'>
<tr>
  <td class='ri'><%= t 'specimen.title' %>:</td>
  <td class='nc'><%= @shipment.speciman.title %></td>
</tr>

<tr>
  <td class='ri'><%= t 'shipments.batch_number' %>:</td>
  <td class='nc'><%= @shipment.batch_number %></td>
</tr>

<tr>
  <td class='ri'><%= t 'shipments.check_number' %>:</td>
  <td class='nc'><%= @shipment.check_number %></td>
</tr>

<tr>
  <td class='ri'><%= t 'shipments.manufdt' %>:</td>
  <td class='nc'><%= @shipment.manufdt %></td>
</tr>

<tr>
  <td class='ri'><%= t 'shipments.releasedt' %>:</td>
  <td class='nc'><%= @shipment.releasedt %></td>
</tr>

<tr>
  <td class='ri'><%= t 'shipments.expiredt' %>:</td>
  <td class='nc'><%= @shipment.expiredt %></td>
</tr>
</table>

app/views/shipments/edit.html.erb
<h1>Editing shipment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@speciman, @shipment] %> |
<%= link_to 'Back', speciman_shipments_path(@speciman) %> |
<%= link_to 'Destroy', [@speciman, @shipment], :confirm => 'Are you sure?', :method => :delete %>

app/views/shipments/index.html.erb
<h1><%= @speciman.title %> <span style='font-size: 0.5em; font-weight: normal;'><%= t 'shipments.nav' %></span></h1>

<table>
  <tr>
    <th><%= t 'shipments.batch_number' %></th>
    <th><%= t 'shipments.check_number' %></th>
    <th><%= t 'shipments.manufdt' %></th>
    <th><%= t 'shipments.releasedt' %></th>
    <th><%= t 'shipments.expiredt' %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shipments.each do |shipment| %>
  <tr>
    <td><%= shipment.batch_number %></td>
    <td><%= shipment.check_number %></td>
    <td><%= shipment.manufdt %></td>
    <td><%= shipment.releasedt %></td>
    <td><%= shipment.expiredt %></td>
    <td><%= link_to 'Show', [@speciman, shipment] %></td>
    <td><%= link_to 'Edit', edit_speciman_shipment_path(shipment.speciman, shipment) %></td>
    <td><%= link_to 'passport', passport_path(shipment.speciman, shipment), :target => '_blank' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to (t 'shipments.nav-new'), new_speciman_shipment_path(@speciman) %>

app/views/shipments/new.html.erb
<h1>New shipment</h1>

<%= render 'form' %>

<%= link_to 'Back', speciman_shipments_path(@speciman) %>

app/views/shipments/passport.html.erb
<p ><%= '' %></p>

<p>
  <b></b>
  <%= '' %>
</p>

<div class='yy lbl' id='batch_label'>
  Серия № ________________________
</div>
<div class='yy val' id='batch_num'>
  <%= @shipment.batch_number %>
</div>

<div class='yy lbl' id='check_label'>
  Контрольный номер ______________
</div>
<div class='yy val' id='check_num'>
  <%= @shipment.check_number %>
</div>

<div class='yy lbl' id='manufdt_label'>
  Дата изготовления __________________________
</div>
<div class='yy val' id='manufdt_val'>
  <%= Russian::strftime(@shipment.manufdt, "%d %B %Y") %>
</div>



<p>
  <b><%= '' %></b>
  <%= '' %>
</p>

<p>
  <b><%= '' %></b>
  <%= '' %>
</p>



<table class='ppt'>
<tr><th>№ пп</th><th>Наименование показателей</th><th>Требования по НТД</th><th>Результаты контроля ОБТК</th></tr>

<tr><td>1.</td><td>Описание</td><td>Пористая масса, порошкообразная или в виде таблетки светло-желтого цвета. Гигроскопична.</td><td>Пористая масса, порошкообразная или в виде таблетки светло-желтого цвета. Гигроскопична.</td></tr>
</table>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => @shipment %>


<%= link_to 'Edit', edit_speciman_shipment_path(@speciman, @shipment) %> |
<%= link_to 'Back', speciman_shipments_path(@speciman) %>